# encoding: UTF-8
# Generated by tools/support/quiz_pack_writer.rb; do not edit the checksum by hand.
# Source: Andrzej Sapkowski: opowiadania i powieści; autorska redakcja pytań i odpowiedzi
require_relative "../lib/game_content"
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "quiz.witcher.books.pl",
  set_id: "quiz.witcher.books",
  kind: :quiz,
  language_id: "pl-PL",
  version: 1,
  title: "Wiedźmin — książki",
  game_ids: ["quiz"],
  author: "Power Games",
  license: "See QUIZ_DATA_NOTICE.md; no CC0 or inherited Fandom license claimed",
  entry_count: 1275,
  checksum: "f44884edfb481a051cdf6f818d5dd702f1a6788a3ca4821ad26f792153db8a6a",
  loader: lambda {
    require_relative "quiz_witcher_pl_data"
    GameRoomContent::Packb2f3aa32decbfd64667e7738.load
  }
))
