# encoding: UTF-8
# Generated by tools/support/quiz_pack_writer.rb; do not edit the checksum by hand.
# Source: Andrzej Sapkowski: opowiadania i powieści; autorska redakcja pytań i odpowiedzi
require_relative "../lib/game_content"
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "quiz.witcher.books.pl",
  set_id: "quiz.witcher.books",
  kind: :quiz,
  language_id: "pl-PL",
  version: 1,
  title: "Wiedźmin — książki",
  game_ids: ["quiz"],
  author: "Power Games",
  license: "See QUIZ_DATA_NOTICE.md; no CC0 or inherited Fandom license claimed",
  entry_count: 1457,
  checksum: "d6520037cfd9a0a667043af65d44d2f3cb98e824ba1d1d57449df09478e1671a",
  loader: lambda {
    require_relative "quiz_witcher_pl_data"
    GameRoomContent::Packb2f3aa32decbfd64667e7738.load
  }
))
